######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 16 13:46:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += webkit network

# Input
HEADERS += mainview.h
SOURCES += main.cpp mainview.cpp
