######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 2 21:05:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . .
INCLUDEPATH += .
CONFIG += uitools
QT += svg

# Input
HEADERS += renderer.h
SOURCES += main.cpp renderer.cpp
