######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 7 11:49:51 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/qt-examples/qt-bugs/qregexp-bug/. .

# Input
SOURCES += main.cpp
