######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 10 16:04:25 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/qt-examples/webthumbnails/. .

QT += webkit

# Input
HEADERS += kwebthumbnailer.h toplevel.h
SOURCES += kwebthumbnailer.cpp toplevel.cpp main.cpp
