######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 9 11:48:02 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += script
QT += network

# Input
HEADERS += proxyautoconfig.h
SOURCES += proxyautoconfig.cpp main.cpp
