######################################################################
# Automatically generated by qmake (2.01a) Sun May 22 16:24:55 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += monitortest.h sslcertificatemonitor.h
SOURCES += main.cpp monitortest.cpp sslcertificatemonitor.cpp
