######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 22 14:24:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += resizer.h viewer.h
FORMS += viewer.ui
SOURCES += main.cpp resizer.cpp viewer.cpp
