######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 5 13:32:14 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/qtwebkitextension/. .

QT += webkit

# Input
HEADERS += testobject.h
SOURCES += main.cpp testobject.cpp
