######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 4 13:01:20 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += animator.h
SOURCES += animator.cpp main.cpp
