######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 5 10:35:48 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core script

# Input
HEADERS += foo.h
SOURCES += foo.cpp main.cpp
