######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 8 15:16:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui
QT += network

# Input
HEADERS += connector.h
SOURCES += connector.cpp main.cpp
