######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 2 14:52:34 2013
######################################################################

TEMPLATE = app
TARGET = sslserver
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += sslserver.h
SOURCES += main.cpp sslserver.cpp
