######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 6 16:53:16 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/jsui/. .

QT += script
CONFIG += uitools

# Input
HEADERS += scriptui.h
SOURCES += main.cpp scriptui.cpp
