######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 26 13:08:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += draggable.h
SOURCES += draggable.cpp main.cpp
