######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 2 22:18:22 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/qt-examples/sitespecificbrowser/. .

QT += webkit

# Input
HEADERS += toplevel.h
SOURCES += main.cpp toplevel.cpp
