######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 8 13:44:15 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/qt-examples/qtwebkitplugins/. .

QT += webkit

# Input
HEADERS += pluginfactory.h
SOURCES += main.cpp pluginfactory.cpp
