######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 20 12:30:43 2010
######################################################################

TEMPLATE = app
TARGET = sslsocket
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
SOURCES += main.cpp
