######################################################################
# Automatically generated by qmake (3.0) Sun May 25 11:42:18 2014
######################################################################

TEMPLATE = app
TARGET = httpserver
INCLUDEPATH += .

QT -= gui
QT += network

# Input
HEADERS += httprequesthandler.h httpserver.h qsslserver.h httpsserver.h
SOURCES += httprequesthandler.cpp httpserver.cpp main.cpp qsslserver.cpp httpsserver.cpp
